/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TiendasRouteImport } from './routes/tiendas'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PrensaRouteImport } from './routes/prensa'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EnviosRouteImport } from './routes/envios'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CambiosDevolucionesRouteImport } from './routes/cambios-devoluciones'
import { Route as AvisoRouteImport } from './routes/aviso'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacksIndexRouteImport } from './routes/packs/index'
import { Route as DropsIndexRouteImport } from './routes/drops/index'
import { Route as CuentaIndexRouteImport } from './routes/cuenta/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as PacksIdRouteImport } from './routes/packs/$id'
import { Route as DropsIdRouteImport } from './routes/drops/$id'
import { Route as CuentaPerfilRouteImport } from './routes/cuenta/perfil'
import { Route as CuentaPedidosRouteImport } from './routes/cuenta/pedidos'
import { Route as CuentaDireccionesRouteImport } from './routes/cuenta/direcciones'
import { Route as CollectionsHandleRouteImport } from './routes/collections/$handle'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminTallasRouteImport } from './routes/admin/tallas'
import { Route as AdminConfiguracionRouteImport } from './routes/admin/configuracion'
import { Route as AdminColoresRouteImport } from './routes/admin/colores'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminProductosIndexRouteImport } from './routes/admin/productos/index'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin/pedidos/index'
import { Route as AdminPacksIndexRouteImport } from './routes/admin/packs/index'
import { Route as AdminDropsIndexRouteImport } from './routes/admin/drops/index'
import { Route as AdminProductosNuevoRouteImport } from './routes/admin/productos/nuevo'
import { Route as AdminProductosIdRouteImport } from './routes/admin/productos/$id'
import { Route as AdminPedidosIdRouteImport } from './routes/admin/pedidos/$id'
import { Route as AdminPacksNuevoRouteImport } from './routes/admin/packs/nuevo'
import { Route as AdminPacksIdRouteImport } from './routes/admin/packs/$id'
import { Route as AdminDropsNuevoRouteImport } from './routes/admin/drops/nuevo'
import { Route as AdminDropsIdRouteImport } from './routes/admin/drops/$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendasRoute = TiendasRouteImport.update({
  id: '/tiendas',
  path: '/tiendas',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PrensaRoute = PrensaRouteImport.update({
  id: '/prensa',
  path: '/prensa',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiosDevolucionesRoute = CambiosDevolucionesRouteImport.update({
  id: '/cambios-devoluciones',
  path: '/cambios-devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoRoute = AvisoRouteImport.update({
  id: '/aviso',
  path: '/aviso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksIndexRoute = PacksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PacksRoute,
} as any)
const DropsIndexRoute = DropsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DropsRoute,
} as any)
const CuentaIndexRoute = CuentaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CuentaRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksIdRoute = PacksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PacksRoute,
} as any)
const DropsIdRoute = DropsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DropsRoute,
} as any)
const CuentaPerfilRoute = CuentaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaPedidosRoute = CuentaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaDireccionesRoute = CuentaDireccionesRouteImport.update({
  id: '/direcciones',
  path: '/direcciones',
  getParentRoute: () => CuentaRoute,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTallasRoute = AdminTallasRouteImport.update({
  id: '/tallas',
  path: '/tallas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColoresRoute = AdminColoresRouteImport.update({
  id: '/colores',
  path: '/colores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosIndexRoute = AdminProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacksIndexRoute = AdminPacksIndexRouteImport.update({
  id: '/packs/',
  path: '/packs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDropsIndexRoute = AdminDropsIndexRouteImport.update({
  id: '/drops/',
  path: '/drops/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosNuevoRoute = AdminProductosNuevoRouteImport.update({
  id: '/productos/nuevo',
  path: '/productos/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosIdRoute = AdminProductosIdRouteImport.update({
  id: '/productos/$id',
  path: '/productos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacksNuevoRoute = AdminPacksNuevoRouteImport.update({
  id: '/packs/nuevo',
  path: '/packs/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacksIdRoute = AdminPacksIdRouteImport.update({
  id: '/packs/$id',
  path: '/packs/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDropsNuevoRoute = AdminDropsNuevoRouteImport.update({
  id: '/drops/nuevo',
  path: '/drops/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDropsIdRoute = AdminDropsIdRouteImport.update({
  id: '/drops/$id',
  path: '/drops/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso': typeof AvisoRoute
  '/cambios-devoluciones': typeof CambiosDevolucionesRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/cuenta': typeof CuentaRouteWithChildren
  '/drops': typeof DropsRouteWithChildren
  '/envios': typeof EnviosRoute
  '/faq': typeof FaqRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/packs': typeof PacksRouteWithChildren
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/prensa': typeof PrensaRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/tiendas': typeof TiendasRoute
  '/wishlist': typeof WishlistRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/colores': typeof AdminColoresRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/tallas': typeof AdminTallasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/cuenta/direcciones': typeof CuentaDireccionesRoute
  '/cuenta/pedidos': typeof CuentaPedidosRoute
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/drops/$id': typeof DropsIdRoute
  '/packs/$id': typeof PacksIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cuenta/': typeof CuentaIndexRoute
  '/drops/': typeof DropsIndexRoute
  '/packs/': typeof PacksIndexRoute
  '/admin/drops/$id': typeof AdminDropsIdRoute
  '/admin/drops/nuevo': typeof AdminDropsNuevoRoute
  '/admin/packs/$id': typeof AdminPacksIdRoute
  '/admin/packs/nuevo': typeof AdminPacksNuevoRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/productos/$id': typeof AdminProductosIdRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/drops/': typeof AdminDropsIndexRoute
  '/admin/packs/': typeof AdminPacksIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/productos/': typeof AdminProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso': typeof AvisoRoute
  '/cambios-devoluciones': typeof CambiosDevolucionesRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/envios': typeof EnviosRoute
  '/faq': typeof FaqRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/prensa': typeof PrensaRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/tiendas': typeof TiendasRoute
  '/wishlist': typeof WishlistRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/colores': typeof AdminColoresRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/tallas': typeof AdminTallasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/cuenta/direcciones': typeof CuentaDireccionesRoute
  '/cuenta/pedidos': typeof CuentaPedidosRoute
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/drops/$id': typeof DropsIdRoute
  '/packs/$id': typeof PacksIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/cuenta': typeof CuentaIndexRoute
  '/drops': typeof DropsIndexRoute
  '/packs': typeof PacksIndexRoute
  '/admin/drops/$id': typeof AdminDropsIdRoute
  '/admin/drops/nuevo': typeof AdminDropsNuevoRoute
  '/admin/packs/$id': typeof AdminPacksIdRoute
  '/admin/packs/nuevo': typeof AdminPacksNuevoRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/productos/$id': typeof AdminProductosIdRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/drops': typeof AdminDropsIndexRoute
  '/admin/packs': typeof AdminPacksIndexRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
  '/admin/productos': typeof AdminProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso': typeof AvisoRoute
  '/cambios-devoluciones': typeof CambiosDevolucionesRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/cuenta': typeof CuentaRouteWithChildren
  '/drops': typeof DropsRouteWithChildren
  '/envios': typeof EnviosRoute
  '/faq': typeof FaqRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/packs': typeof PacksRouteWithChildren
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/prensa': typeof PrensaRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/tiendas': typeof TiendasRoute
  '/wishlist': typeof WishlistRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/colores': typeof AdminColoresRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/tallas': typeof AdminTallasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/cuenta/direcciones': typeof CuentaDireccionesRoute
  '/cuenta/pedidos': typeof CuentaPedidosRoute
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/drops/$id': typeof DropsIdRoute
  '/packs/$id': typeof PacksIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cuenta/': typeof CuentaIndexRoute
  '/drops/': typeof DropsIndexRoute
  '/packs/': typeof PacksIndexRoute
  '/admin/drops/$id': typeof AdminDropsIdRoute
  '/admin/drops/nuevo': typeof AdminDropsNuevoRoute
  '/admin/packs/$id': typeof AdminPacksIdRoute
  '/admin/packs/nuevo': typeof AdminPacksNuevoRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/productos/$id': typeof AdminProductosIdRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/drops/': typeof AdminDropsIndexRoute
  '/admin/packs/': typeof AdminPacksIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/productos/': typeof AdminProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aviso'
    | '/cambios-devoluciones'
    | '/checkout'
    | '/contacto'
    | '/cookies'
    | '/cuenta'
    | '/drops'
    | '/envios'
    | '/faq'
    | '/historia'
    | '/login'
    | '/packs'
    | '/pedido-confirmado'
    | '/prensa'
    | '/privacidad'
    | '/terminos'
    | '/tiendas'
    | '/wishlist'
    | '/admin/clientes'
    | '/admin/colores'
    | '/admin/configuracion'
    | '/admin/tallas'
    | '/auth/callback'
    | '/collections/$handle'
    | '/cuenta/direcciones'
    | '/cuenta/pedidos'
    | '/cuenta/perfil'
    | '/drops/$id'
    | '/packs/$id'
    | '/products/$slug'
    | '/admin/'
    | '/cuenta/'
    | '/drops/'
    | '/packs/'
    | '/admin/drops/$id'
    | '/admin/drops/nuevo'
    | '/admin/packs/$id'
    | '/admin/packs/nuevo'
    | '/admin/pedidos/$id'
    | '/admin/productos/$id'
    | '/admin/productos/nuevo'
    | '/admin/drops/'
    | '/admin/packs/'
    | '/admin/pedidos/'
    | '/admin/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso'
    | '/cambios-devoluciones'
    | '/checkout'
    | '/contacto'
    | '/cookies'
    | '/envios'
    | '/faq'
    | '/historia'
    | '/login'
    | '/pedido-confirmado'
    | '/prensa'
    | '/privacidad'
    | '/terminos'
    | '/tiendas'
    | '/wishlist'
    | '/admin/clientes'
    | '/admin/colores'
    | '/admin/configuracion'
    | '/admin/tallas'
    | '/auth/callback'
    | '/collections/$handle'
    | '/cuenta/direcciones'
    | '/cuenta/pedidos'
    | '/cuenta/perfil'
    | '/drops/$id'
    | '/packs/$id'
    | '/products/$slug'
    | '/admin'
    | '/cuenta'
    | '/drops'
    | '/packs'
    | '/admin/drops/$id'
    | '/admin/drops/nuevo'
    | '/admin/packs/$id'
    | '/admin/packs/nuevo'
    | '/admin/pedidos/$id'
    | '/admin/productos/$id'
    | '/admin/productos/nuevo'
    | '/admin/drops'
    | '/admin/packs'
    | '/admin/pedidos'
    | '/admin/productos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aviso'
    | '/cambios-devoluciones'
    | '/checkout'
    | '/contacto'
    | '/cookies'
    | '/cuenta'
    | '/drops'
    | '/envios'
    | '/faq'
    | '/historia'
    | '/login'
    | '/packs'
    | '/pedido-confirmado'
    | '/prensa'
    | '/privacidad'
    | '/terminos'
    | '/tiendas'
    | '/wishlist'
    | '/admin/clientes'
    | '/admin/colores'
    | '/admin/configuracion'
    | '/admin/tallas'
    | '/auth/callback'
    | '/collections/$handle'
    | '/cuenta/direcciones'
    | '/cuenta/pedidos'
    | '/cuenta/perfil'
    | '/drops/$id'
    | '/packs/$id'
    | '/products/$slug'
    | '/admin/'
    | '/cuenta/'
    | '/drops/'
    | '/packs/'
    | '/admin/drops/$id'
    | '/admin/drops/nuevo'
    | '/admin/packs/$id'
    | '/admin/packs/nuevo'
    | '/admin/pedidos/$id'
    | '/admin/productos/$id'
    | '/admin/productos/nuevo'
    | '/admin/drops/'
    | '/admin/packs/'
    | '/admin/pedidos/'
    | '/admin/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvisoRoute: typeof AvisoRoute
  CambiosDevolucionesRoute: typeof CambiosDevolucionesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  CookiesRoute: typeof CookiesRoute
  CuentaRoute: typeof CuentaRouteWithChildren
  DropsRoute: typeof DropsRouteWithChildren
  EnviosRoute: typeof EnviosRoute
  FaqRoute: typeof FaqRoute
  HistoriaRoute: typeof HistoriaRoute
  LoginRoute: typeof LoginRoute
  PacksRoute: typeof PacksRouteWithChildren
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  PrensaRoute: typeof PrensaRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  TiendasRoute: typeof TiendasRoute
  WishlistRoute: typeof WishlistRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiendas': {
      id: '/tiendas'
      path: '/tiendas'
      fullPath: '/tiendas'
      preLoaderRoute: typeof TiendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prensa': {
      id: '/prensa'
      path: '/prensa'
      fullPath: '/prensa'
      preLoaderRoute: typeof PrensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambios-devoluciones': {
      id: '/cambios-devoluciones'
      path: '/cambios-devoluciones'
      fullPath: '/cambios-devoluciones'
      preLoaderRoute: typeof CambiosDevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso': {
      id: '/aviso'
      path: '/aviso'
      fullPath: '/aviso'
      preLoaderRoute: typeof AvisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/': {
      id: '/packs/'
      path: '/'
      fullPath: '/packs/'
      preLoaderRoute: typeof PacksIndexRouteImport
      parentRoute: typeof PacksRoute
    }
    '/drops/': {
      id: '/drops/'
      path: '/'
      fullPath: '/drops/'
      preLoaderRoute: typeof DropsIndexRouteImport
      parentRoute: typeof DropsRoute
    }
    '/cuenta/': {
      id: '/cuenta/'
      path: '/'
      fullPath: '/cuenta/'
      preLoaderRoute: typeof CuentaIndexRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$id': {
      id: '/packs/$id'
      path: '/$id'
      fullPath: '/packs/$id'
      preLoaderRoute: typeof PacksIdRouteImport
      parentRoute: typeof PacksRoute
    }
    '/drops/$id': {
      id: '/drops/$id'
      path: '/$id'
      fullPath: '/drops/$id'
      preLoaderRoute: typeof DropsIdRouteImport
      parentRoute: typeof DropsRoute
    }
    '/cuenta/perfil': {
      id: '/cuenta/perfil'
      path: '/perfil'
      fullPath: '/cuenta/perfil'
      preLoaderRoute: typeof CuentaPerfilRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/pedidos': {
      id: '/cuenta/pedidos'
      path: '/pedidos'
      fullPath: '/cuenta/pedidos'
      preLoaderRoute: typeof CuentaPedidosRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/direcciones': {
      id: '/cuenta/direcciones'
      path: '/direcciones'
      fullPath: '/cuenta/direcciones'
      preLoaderRoute: typeof CuentaDireccionesRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tallas': {
      id: '/admin/tallas'
      path: '/tallas'
      fullPath: '/admin/tallas'
      preLoaderRoute: typeof AdminTallasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colores': {
      id: '/admin/colores'
      path: '/colores'
      fullPath: '/admin/colores'
      preLoaderRoute: typeof AdminColoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos/': {
      id: '/admin/productos/'
      path: '/productos'
      fullPath: '/admin/productos/'
      preLoaderRoute: typeof AdminProductosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packs/': {
      id: '/admin/packs/'
      path: '/packs'
      fullPath: '/admin/packs/'
      preLoaderRoute: typeof AdminPacksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drops/': {
      id: '/admin/drops/'
      path: '/drops'
      fullPath: '/admin/drops/'
      preLoaderRoute: typeof AdminDropsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos/nuevo': {
      id: '/admin/productos/nuevo'
      path: '/productos/nuevo'
      fullPath: '/admin/productos/nuevo'
      preLoaderRoute: typeof AdminProductosNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos/$id': {
      id: '/admin/productos/$id'
      path: '/productos/$id'
      fullPath: '/admin/productos/$id'
      preLoaderRoute: typeof AdminProductosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packs/nuevo': {
      id: '/admin/packs/nuevo'
      path: '/packs/nuevo'
      fullPath: '/admin/packs/nuevo'
      preLoaderRoute: typeof AdminPacksNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packs/$id': {
      id: '/admin/packs/$id'
      path: '/packs/$id'
      fullPath: '/admin/packs/$id'
      preLoaderRoute: typeof AdminPacksIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drops/nuevo': {
      id: '/admin/drops/nuevo'
      path: '/drops/nuevo'
      fullPath: '/admin/drops/nuevo'
      preLoaderRoute: typeof AdminDropsNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drops/$id': {
      id: '/admin/drops/$id'
      path: '/drops/$id'
      fullPath: '/admin/drops/$id'
      preLoaderRoute: typeof AdminDropsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminColoresRoute: typeof AdminColoresRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminTallasRoute: typeof AdminTallasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDropsIdRoute: typeof AdminDropsIdRoute
  AdminDropsNuevoRoute: typeof AdminDropsNuevoRoute
  AdminPacksIdRoute: typeof AdminPacksIdRoute
  AdminPacksNuevoRoute: typeof AdminPacksNuevoRoute
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminProductosIdRoute: typeof AdminProductosIdRoute
  AdminProductosNuevoRoute: typeof AdminProductosNuevoRoute
  AdminDropsIndexRoute: typeof AdminDropsIndexRoute
  AdminPacksIndexRoute: typeof AdminPacksIndexRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
  AdminProductosIndexRoute: typeof AdminProductosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminColoresRoute: AdminColoresRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminTallasRoute: AdminTallasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDropsIdRoute: AdminDropsIdRoute,
  AdminDropsNuevoRoute: AdminDropsNuevoRoute,
  AdminPacksIdRoute: AdminPacksIdRoute,
  AdminPacksNuevoRoute: AdminPacksNuevoRoute,
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminProductosIdRoute: AdminProductosIdRoute,
  AdminProductosNuevoRoute: AdminProductosNuevoRoute,
  AdminDropsIndexRoute: AdminDropsIndexRoute,
  AdminPacksIndexRoute: AdminPacksIndexRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
  AdminProductosIndexRoute: AdminProductosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CuentaRouteChildren {
  CuentaDireccionesRoute: typeof CuentaDireccionesRoute
  CuentaPedidosRoute: typeof CuentaPedidosRoute
  CuentaPerfilRoute: typeof CuentaPerfilRoute
  CuentaIndexRoute: typeof CuentaIndexRoute
}

const CuentaRouteChildren: CuentaRouteChildren = {
  CuentaDireccionesRoute: CuentaDireccionesRoute,
  CuentaPedidosRoute: CuentaPedidosRoute,
  CuentaPerfilRoute: CuentaPerfilRoute,
  CuentaIndexRoute: CuentaIndexRoute,
}

const CuentaRouteWithChildren =
  CuentaRoute._addFileChildren(CuentaRouteChildren)

interface DropsRouteChildren {
  DropsIdRoute: typeof DropsIdRoute
  DropsIndexRoute: typeof DropsIndexRoute
}

const DropsRouteChildren: DropsRouteChildren = {
  DropsIdRoute: DropsIdRoute,
  DropsIndexRoute: DropsIndexRoute,
}

const DropsRouteWithChildren = DropsRoute._addFileChildren(DropsRouteChildren)

interface PacksRouteChildren {
  PacksIdRoute: typeof PacksIdRoute
  PacksIndexRoute: typeof PacksIndexRoute
}

const PacksRouteChildren: PacksRouteChildren = {
  PacksIdRoute: PacksIdRoute,
  PacksIndexRoute: PacksIndexRoute,
}

const PacksRouteWithChildren = PacksRoute._addFileChildren(PacksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvisoRoute: AvisoRoute,
  CambiosDevolucionesRoute: CambiosDevolucionesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  CookiesRoute: CookiesRoute,
  CuentaRoute: CuentaRouteWithChildren,
  DropsRoute: DropsRouteWithChildren,
  EnviosRoute: EnviosRoute,
  FaqRoute: FaqRoute,
  HistoriaRoute: HistoriaRoute,
  LoginRoute: LoginRoute,
  PacksRoute: PacksRouteWithChildren,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  PrensaRoute: PrensaRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  TiendasRoute: TiendasRoute,
  WishlistRoute: WishlistRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
